from enum import Enum


CONTACT_ENTITY_TYPE = "CONTACT"
CONTACT_PREFERENCE_ENTITY_TYPE = "CONTACT_PREFERENCE"
ADMISSION_LEAD_ENTITY_TYPE = "ADMISSION_LEAD"
WHATSAPP_CHANNEL = "WHATSAPP"


class LeadStatus(str, Enum):
    NEW = "NEW"
    NEEDS_CONTACT = "NEEDS_CONTACT"
    CONTACT_ATTEMPTED = "CONTACT_ATTEMPTED"
    CONNECTED = "CONNECTED"
    INTERESTED = "INTERESTED"
    FOLLOW_UP_REQUIRED = "FOLLOW_UP_REQUIRED"
    DEMO_REGISTERED = "DEMO_REGISTERED"
    DEMO_ATTENDED = "DEMO_ATTENDED"
    ADMISSION_IN_PROGRESS = "ADMISSION_IN_PROGRESS"
    ADMITTED = "ADMITTED"
    NOT_INTERESTED = "NOT_INTERESTED"
    UNRESPONSIVE = "UNRESPONSIVE"
    INVALID_CONTACT = "INVALID_CONTACT"
    DO_NOT_CONTACT = "DO_NOT_CONTACT"
    LOST = "LOST"


class LeadPriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class PreferredMode(str, Enum):
    ONLINE = "ONLINE"
    OFFLINE = "OFFLINE"
    HYBRID = "HYBRID"


class InterestLevel(str, Enum):
    EXPLORING = "EXPLORING"
    INTERESTED = "INTERESTED"
    HIGH = "HIGH"


class ReassignmentStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class ReassignmentReason(str, Enum):
    LANGUAGE_REQUIREMENT = "LANGUAGE_REQUIREMENT"
    COURSE_SPECIALIZATION = "COURSE_SPECIALIZATION"
    COUNSELLOR_UNAVAILABLE = "COUNSELLOR_UNAVAILABLE"
    LEAD_REQUESTED_CHANGE = "LEAD_REQUESTED_CHANGE"
    WORKLOAD = "WORKLOAD"
    WRONG_ASSIGNMENT = "WRONG_ASSIGNMENT"
    OTHER = "OTHER"


class ActivityType(str, Enum):
    CONTACT_CREATED = "CONTACT_CREATED"
    CONTACT_CORRECTED = "CONTACT_CORRECTED"
    CONTACT_NAME_CORRECTED = "CONTACT_NAME_CORRECTED"
    CONTACT_PHONE_CORRECTED = "CONTACT_PHONE_CORRECTED"
    COMMUNICATION_PREFERENCE_CHANGED = "COMMUNICATION_PREFERENCE_CHANGED"
    DO_NOT_CONTACT_ENABLED = "DO_NOT_CONTACT_ENABLED"
    DO_NOT_CONTACT_DISABLED = "DO_NOT_CONTACT_DISABLED"
    LEAD_CREATED = "LEAD_CREATED"
    LEAD_UPDATED = "LEAD_UPDATED"
    LEAD_STATUS_CHANGED = "LEAD_STATUS_CHANGED"
    LEAD_PRIORITY_CHANGED = "LEAD_PRIORITY_CHANGED"
    LEAD_ASSIGNED = "LEAD_ASSIGNED"
    REASSIGNMENT_REQUESTED = "REASSIGNMENT_REQUESTED"
    REASSIGNMENT_APPROVED = "REASSIGNMENT_APPROVED"
    REASSIGNMENT_REJECTED = "REASSIGNMENT_REJECTED"
    REASSIGNMENT_CANCELLED = "REASSIGNMENT_CANCELLED"


class ActorType(str, Enum):
    USER = "USER"
    SYSTEM = "SYSTEM"
